////import createClient from "openapi-fetch";
////import type { paths } from "./my-openapi-3-schema"; // generated by openapi-typescript

//const client = createClient<paths>({ baseUrl: "https://myapi.dev/v1/" });

//const {
//  data, // only present if 2XX response
//  error, // only present if 4XX or 5XX response
//} = await client.GET("/blogposts/{post_id}", {
//  params: {
//    path: { post_id: "123" },
//  },
//});

//await client.PUT("/blogposts", {
//  body: {
//    title: "My New Post",
//  },
//});